Rails/assignments/books_management/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'users/invitations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # scope :rails do
  #  resources :books
  # end

  root "books#show"
  get '/books/index', to: 'books#index' ,as: 'show_books'
  get '/books/new', to: 'books#new' , as: 'new_books'
  post '/books', to: 'books#create'
  get '/books/edit/:id', to: 'books#edit', as: 'books_edit'
  put '/books/:id', to: 'books#update'

  get '/rails/books/index', to: 'books#index' ,as: 'rails_books_index'
  get '/rails/books/new', to: 'books#new' , as: 'rails_new_books'
  post '/rails/books', to: 'books#create' , as: 'rails_books_create'
  get '/rails/books/:id/edit', to: 'books#edit' ,as: 'rails_books_edit'
  put '/rails/books/:id', to: 'books#update' ,as: 'rails_books_update'
  delete '/rails/books/:id', to: 'books#destroy' ,as: 'rails_books_destroy'
  
  get '/profile', to: "books#profile" , as: 'profile'

  patch 'users/update_avatar', to: 'users#update_avatar', as: :update_avatar
  delete 'users/remove_avatar', to: 'users#remove_avatar', as: :remove_avatar

  post 'users/save_attachments', to: 'users#save_attachments', as: :save_attachments_user
  delete 'users/remove_attachments', to: 'users#remove_attachments', as: :remove_attachments_user
end

Rails/assignments/books_management/app/models/book.rb
class Book < ApplicationRecord
end

Rails/assignments/books_management/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable

  validates :name, presence: true
  has_one_attached :avatar

  mount_uploaders :attachments, AttachmentUploader
end

Rails/assignments/books_management/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name , :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name , :avatar])
    devise_parameter_sanitizer.permit(:invite, keys: [:name])
  end
  
end

Rails/assignments/books_management/app/controllers/books_controller.rb
class BooksController < ApplicationController
  # layout "special_layout", only: [:special_action, :another_action]

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new
    @book.title = params[:title]
    @book.author = params[:author]
    @book.genre = params[:genre]
    @book.quantity = params[:quantity]
    if @book.save
      redirect_to books_path
      puts "Book saved successfully" , status: 201
    else
      render :new
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.title = params[:title]
    @book.author = params[:author]
    @book.genre = params[:genre]
    @book.quantity = params[:quantity]
    if @book.save
      redirect_to show_books_path 
      puts "Book updated successfully" , status: 200
      # render plain: "OK"
      # render html: helpers.tag.strong('Not Found')
      # render js: "alert('Hello Rails');"
      # render json: @book
      # render xml: @book

      # render plain: "Hello, world!", content_type: "text/plain"     # :content_type option for render
      # render :show, layout: "special_layout"                        # :layout option for render
      # render :show, layout: false
      # render xml: photo, location: photo_url(photo)                   # :location option for render

      # render action: "empty_list" 
    else
      render :edit
      # render plain: "Failed to update the book.", status: :unprocessable_entity
    end
  end


  def show
    # @book = Book.find_by(id: params[:id])
    # if @book.nil?
    #   @books = Book.all
    #   flash.now[:alert] = "Your book was not found"
    #   render "index"
    # end
  end
  

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to show_books_path
  end

  def profile
  end
end

Rails/assignments/books_management/app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
end

Rails/assignments/books_management/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def update_avatar
    if current_user.update(avatar_params)
      redirect_to edit_user_registration_path, notice: 'Profile picture updated successfully.'
    else
      flash[:alert] = current_user.errors.full_messages.to_sentence
      redirect_to edit_user_registration_path
    end
  end

  def remove_avatar
    current_user.avatar.purge
    redirect_to edit_user_registration_path, notice: 'Profile picture removed successfully.'
  end

  def save_attachments
    @user = current_user
    existing_attachments = @user.attachments
    new_attachments = params[:user][:attachments] || []
    if current_user.update(attachments: existing_attachments + new_attachments)
    # if current_user.update(attachments_params)
      redirect_to root_path, notice: 'Attachments uploaded successfully.'
    else
      flash[:alert] = current_user.errors.full_messages.to_sentence
      redirect_to root_path
    end
  end


def remove_attachments
  attachment_identifiers = params[:user][:remove_attachments] || [] 

  attachment_identifiers.each do |identifier|
    attachment = current_user.attachments.find { |att| att.identifier == identifier }
    if attachment
      attachment.remove! 
    end
  end
  current_user.save

  flash[:notice] = 'Selected attachments successfully removed.'
  redirect_to root_path
end

  
  private

  def avatar_params
    params.require(:user).permit(:avatar)
  end

  def attachments_params
    params.require(:user).permit(attachments: [])
  end
end

Rails/assignments/books_management/app/views/books/_empty_list.html.erb
There are no items in this list <em>yet</em>.

Rails/assignments/books_management/app/views/books/edit.html.erb
<div style="display: flex">
  <div class="container">
    <h2>Update Book</h2>
    <form action="/books/<%= @book.id %>" method="put" class="book-form">
      <div class="form-group">
        <label for="title"> Title: </label>
        <input type="text" id="title" name="title" value="<%= @book.title %>" required>
      </div>
      <div class="form-group">
        <label for="author"> Author: </label>
        <input type="text" id="author" name="author" value="<%= @book.author %>" required>
      </div>
      <div class="form-group">
        <label for="genre"> Genre: </label>
        <input type="text" id="genre" name="genre"  value="<%= @book.genre %>" required>
      </div>
      <div class="form-group">
        <label for="quantity"> Quantity:</label>
        <input type="text" id="quantity" name="quantity" value="<%= @book.quantity %>" required>
      </div>
      <button type="submit" class="submit-btn"> Update </button>
    </form>
    <a style="margin-left: 10px" href="/books/index"> Back </a>
  </div>

  <div class="container">
    <h2>Update Book (Rails form)</h2>
    <%= form_with url: rails_books_update_path(@book.id), method: :put, class: "book-form" do |form| %>
      <div class="form-group">
        <%= form.label :title, "Title:" %>
        <%= form.text_field :title, value: @book.title %> 
      </div>
      <div class="form-group">
        <%= form.label :author, "Author:" %>
        <%= form.text_field :author , value: @book.author%>
      </div>
      <div class="form-group">
        <%= form.label :genre, "Genre:" %>
        <%= form.text_field :genre , value: @book.genre%>
      </div>
      <div class="form-group">
        <%= form.label :quantity, "Quantity:" %>
        <%= form.text_field :quantity , value: @book.quantity%>
      </div>
      <%= form.submit "Save" ,class: "submit-btn" %>
    <% end %>
    <%= link_to "Back" , rails_books_index_path, style: "margin-left: 10px"%>
  </div>
<div>

Rails/assignments/books_management/app/views/books/index.html.erb
<h2 style="margin-left: 10px">Books</h2>
<table class="table-container">
  <thead>
    <tr>
      <th> Title </th>
      <th> Author </th>
      <th> Genre </th>  
      <th> Quantity </th>
      <th> Edit (normal) </th>
      <th> Edit (rails) </th>
      <th> Delete </th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.genre %></td>
        <td style="text-align: center"><%= book.quantity %></td>
        <td style="text-align: center">
            <%= link_to "Edit", books_edit_path(book.id) %>
        </td>
        <td style="text-align: center">
          <%# link_to_if(book.quantity < 20, "Edit", rails_books_edit_path(book.id)) %>
          <%# link_to_unless(book.quantity == 14, "Edit", rails_books_edit_path(book.id)) %>
          <%= link_to "Edit", rails_books_edit_path(book.id) %>
        </td>
        <td style="text-align: center">
          <%= link_to "Delete", rails_books_destroy_path(book.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<a style="margin-left: 10px" href="/books/new"> Add New Book</a>
<a style="margin-left: 10px" href="/"> Go Back</a>  <br/>

<%= link_to "+ Add New book", rails_new_books_path , style: "margin-left: 10px" %>
<%= link_to "Go Back", root_path , style: "margin-left: 10px" %>

Rails/assignments/books_management/app/views/books/new.html.erb
<div style="display: flex">
  <div class="container">
    <h2>Add New Book</h2>
    <form action="/books" method="post" class="book-form">
      <div class="form-group">
        <label for="title"> Title: </label>
        <input type="text" id="title" name="title" required>
      </div>

      <div class="form-group">
        <label for="author"> Author: </label>
        <input type="text" id="author" name="author" required>
      </div>

      <div class="form-group">
        <label for="genre"> Genre: </label>
        <input type="text" id="genre" name="genre" required>
      </div>

      <div class="form-group">
        <label for="quantity"> Quantity:</label>
        <input type="text" id="quantity" name="quantity" required>
      </div>

      <button type="submit" class="submit-btn"> Save </button>
    </form>
    <a style="margin-left: 10px" href="/"> Back </a>
  </div>

  <div class="container">
    <h2>Add New Book (Rails form)</h2>
    <%= form_with url: "/rails/books", method: :post, class: "book-form" do |form| %>
      <div class="form-group">
        <%= form.label :title, "Title:" %>
        <%= form.text_field :title %>
      </div>
      <div class="form-group">
        <%= form.label :author, "Author:" %>
        <%= form.text_field :author %>
      </div>
      <div class="form-group">
        <%= form.label :genre, "Genre:" %>
        <%= form.text_field :genre %>
      </div>
      <div class="form-group">
        <%= form.label :quantity, "Quantity:" %>
        <%= form.text_field :quantity %>
      </div>
      <%= form.submit "Save" ,class: "submit-btn" %>
    <% end %>
    <%= link_to "Back" , root_path , style: "margin-left: 10px"%>
  </div>
<div>

Rails/assignments/books_management/app/views/books/profile.html.erb
<div class="container">
  <h2>Tesing Inputs in Form</h2>
  <%= form_with url: "/books/12", method: :put, class: "book-form" do |form| %>
    <div class="form-group">
      <%= form.label :title, "Book Title:" %>
      <%= form.text_field :title %>
    </div>
    <div class="form-group">
      <%= form.check_box :pet_dog %>
      <%= form.label :pet_dog, "I own a dog" %>
      <%= form.check_box :pet_cat %>
      <%= form.label :pet_cat, "I own a cat" %>
    </div>
    <div class="form-group">
      <%= form.radio_button :age, "child" %>
      <%= form.label :age_child, "I am younger than 20" %>
      <%= form.radio_button :age, "adult" %>
      <%= form.label :age_adult, "I am older than 20" %>
    </div>
    <div class="form-group">
      <%= form.label :message, "Message:" %>
      <%= form.text_area :message, size: "70x5" %>
    </div>
    <div class="form-group">
      <%= form.hidden_field :parent_id, value: "foo" %>
    </div>
    <div class="form-group">
      <%= form.label :password, "Password:" %>
      <%= form.password_field :password %>
    </div>
    <div class="form-group">
      <%= form.label :price, "Price:" %>
      <%= form.number_field :price, in: 1.0..20.0, step: 0.5 %>
    </div>
    <div class="form-group">
      <%= form.label :discount, "Discount:" %>
      <%= form.range_field :discount, in: 1..100 %>
    </div>
    <div class="form-group">
      <%= form.label :born_on, "Born On:" %>
      <%= form.date_field :born_on %>
    </div>
    <div class="form-group">
      <%= form.label :started_at, "Started At:" %>
      <%= form.time_field :started_at %>
    </div>
    <div class="form-group">
      <%= form.label :graduation_day, "Graduation Day:" %>
      <%= form.datetime_local_field :graduation_day %>
    </div>
    <div class="form-group">
      <%= form.label :birthday_month, "Birthday Month:" %>
      <%= form.month_field :birthday_month %>
    </div>
    <div class="form-group">
      <%= form.label :birthday_week, "Birthday Week:" %>
      <%= form.week_field :birthday_week %>
    </div>
    <div class="form-group">
      <%= form.label :name, "Search Name:" %>
      <%= form.search_field :name %>
    </div>
    <div class="form-group">
      <%= form.label :address, "Email Address:" %>
      <%= form.email_field :address %>
    </div>
    <div class="form-group">
      <%= form.label :phone, "Phone Number:" %>
      <%= form.telephone_field :phone %>
    </div>
    <div class="form-group">
      <%= form.label :favorite_color, "Favorite Color:" %>
      <%= form.color_field :favorite_color %>
    </div>
    <div class="form-group">
      <%= form.label :homepage, "Homepage URL:" %>
      <%= form.url_field :homepage %>
    </div>
    <div class="form-group">
      <%= form.label :city, "City:" %>
      <%= form.select :city, [["Berlin", "BE"], ["Chicago", "CHI"], ["Madrid", "MD"]]%>
      <%= form.select :city,
      {
        "Europe" => [ ["Berlin", "BE"], ["Madrid", "MD"] ],
        "North America" => [ ["Chicago", "CHI"] ],
      },
      selected: "CHI" %>
    </div>
    <div class="form-group">
      <%= form.label :time_zone, "Time Zone:" %>
      <%= form.time_zone_select :time_zone %>
    </div>
    <div class="form-group">
      <%= form.label :birth_date, "Birth Date:" %>
      <%= form.date_select :birth_date %>
    </div>
    <div class="form-group">
      <%= form.label :birth_year, "Birth Year:" %>
      <%= select_year 1999, prefix: "party" %>
    </div>
    <div class="form-group">
      <%= form.label :picture, "Picture:" %>
      <%= form.file_field :picture %>
    </div>
    <div class="form-group">
      <%= form.submit "Save", class: "submit-btn" %>
    </div>
    <div>
      <%= link_to "Back", "/" %>
    </div>
  <% end %>
</div>

<%# image_tag "icons/delete.gif" %>

Rails/assignments/books_management/app/views/books/show.html.erb
<br/>
<div class="button-group">
  <a href="/books/new" class="button-link">
    <button class="button">Add New Book</button>
  </a>
  <a href="/books/index" class="button-link">
    <button class="button">View All Books</button>
  </a>
</div><br/>

<div class="button-group">
  <%= button_to "New" , rails_new_books_path , method: :get, class: "button-link" %>
  <%= button_to "View All" , rails_books_index_path , method: :get , class: "button-link"%>
</div><br/>


<% if current_user && current_user.avatar.attached? %>
  <%= image_tag current_user.avatar.variant(resize_to_fit: [100, 100]).processed %>
  <%= image_tag current_user.avatar.variant(resize_to_limit: [100, 100], rotate: 90).processed %> 
  <%= image_tag current_user.avatar.variant(resize_and_pad: [100, 100], rotate: 180).processed %>
  <%= image_tag current_user.avatar.variant(resize_to_fill: [100, 100], rotate: 270).processed %>
<% end %><br/>

<div>
  <%= link_to "tel:+919588169118" do %>
    <strong>Phone me:</strong> <span>9588169118</span>
  <% end %>
</div>
<div>
  <%= link_to "sms:+919588169118" do %>
    <strong>Text me:</strong> <span>9588169118</span>
  <% end %>
</div>
<div>
  <%= mail_to "nishchay.gupta@berylsystems.com" do %>
    <strong>Email me:</strong> <span>nishchay.gupta@berylsystems.com</span>
  <% end %>
</div><br/>

<% if current_user %>
  <%= form_for current_user, url: save_attachments_user_path, html: { multipart: true, method: :post } do |f| %>
    <%= f.label :attachments, "Upload Attachments" %><br/>
    <%= f.file_field :attachments, multiple: true ,required: true%><br/>
    <%= f.submit "Upload Attachments" %>
  <% end %>
<% end %>

<%= form_with model: current_user, url: remove_attachments_user_path, method: :delete do |f| %>
  <h3>Your Attachments:</h3>
  <% current_user.attachments.each do |attachment| %>
    <% if attachment.present? %>
      <%= image_tag attachment.url %><br/>
      <%= f.check_box :remove_attachments, { multiple: true, value: attachment.identifier } %>
      <%= f.label :remove_attachments, "Remove #{attachment.identifier}" %>
    <% end %>
  <% end %><br/><br/>
  <%= f.submit 'Remove Selected Attachments' %>
<% end %>

Rails/assignments/books_management/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "books", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navbar">
      <div class="navbar-brand">
        <i class="fas fa-book"></i>
        <h1>Books Management</h1>
      </div>
      <div class="navbar-links">
        <%= link_to "Home", root_path %>
        <%= link_to "Books" , rails_books_index_path %>
        
        <% unless user_signed_in? %>
          <%= link_to "Log In", new_user_session_path %>
        <% end %>

        <% if user_signed_in? %>
          <%= link_to "Invite", new_user_invitation_path %>
          <%= link_to "Profile" , edit_user_registration_path %>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, redirect_to: user_session_path ,data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        <% end %>

      </div>
    </div>
    <%= yield %>
  </body>
</html>

Rails/assignments/books_management/app/views/layouts/special_layout.html.erb
<!-- app/views/layouts/special_layout.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>Special Layout</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <header>
    <h1>This is the Special Layout</h1>
  </header>
  
  <%= yield %>

  <footer>
    <p>Special footer content</p>
  </footer>
</body>
</html>

Rails/assignments/books_management/app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h4 style="margin-top: -5px">
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h4>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li style="color: red"><%= message %></li>
      <% end %>
    </ul><br/>
  </div>
<% end %>

Rails/assignments/books_management/app/views/users/shared/_links.html.erb
<div style="margin-left: 10px">
  <%- if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name) %><br />
  <% end %>

  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name) %><br />
  <% end %>

  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
  <% end %>

  <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
  <% end %>

  <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
  <% end %>

  <%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
      <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
    <% end %>
  <% end %>
<div>